### ISSUE TITLE
ZF\Configuration\ConfigWriter replacement is inconvenient

### ISSUE THREAD

**Issue by weierophinney** [laminas-api-tools/api-tools-configuration#5]
Is there a reason, why `ZF\Configuration` uses `Zend\Config\Writer\WriterInterface` (good) for extensibility, but provides this service via `Zend\ModuleManager\Feature\ServiceProviderInterface` API (bad)  and not simply via module configuration? 

This makes overriding with another `Zend\Config\Writer\WriterInterface`-implementation less convenient. You have to either allow overriding (bad, affects everything in service manager) or hook up to certain events to make modification.

---

Originally posted by @akomm at https://github.com/zfcampus/zf-configuration/issues/16

**Comment by weierophinney** [comment]
The answer: It was overlooked.

Please feel free to submit a pull request that changes the behavior.


---

Originally posted by @weierophinney at https://github.com/zfcampus/zf-configuration/issues/16#issuecomment-232468615

**Comment by Xerkus** [comment]
This was fixed by 1.2.0 in 2016 but issue was left dangling and eventually migrated here.
